/*
Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

Tests:
Waiting:1. fiboEvenSum(10) should return a number.
Waiting:2. Your function should return an even value.
Waiting:3. Your function should sum the even-valued Fibonacci numbers: fiboEvenSum(8) should return 10.
Waiting:4. fiboEvenSum(10) should return 10.
Waiting:5. fiboEvenSum(34) should return 44.
Waiting:6. fiboEvenSum(60) should return 44.
Waiting:7. fiboEvenSum(1000) should return 798.
Waiting:8. fiboEvenSum(100000) should return 60696.
Waiting:9. fiboEvenSum(4000000) should return 4613732.
*/

console.log(`evenSum(10): `+ fiboEvenSum(10))
console.log(`evenSum(34): `+ fiboEvenSum(34))
console.log(`evenSum(60): `+ fiboEvenSum(60))
console.log(`evenSum(1000): `+ fiboEvenSum(1000))

console.log(`fibo1(7): ${fibo1(7)}`)
console.log(fibo1(4))
console.log(fibo1(6))
console.log(fibo1(8))

console.log(`fibo2(7): ${fibo2(7)}`)
console.log(fibo2(4))
console.log(fibo2(5))
console.log(fibo2(6))


function fibo1(n){
    let a = 1;
    let b = 2;
    let c = a + b;

    for(let i = 2; i < n-2; i++){
        a = b;
        b = c;
        c = a + b;
    }
    return c;
}

function fibo2(n){
    if(n <= 0) return 0;
    if( n == 1) return 1;
    return fibo2(n-1) + fibo2(n-2);
}

function fiboEvenSum(n){
    if(n <= 0) return 0;
    if( n == 1) return 1;

    let a = 1;
    let b = 2;
    let c = a + b;

    let evenSum = 2;
    let evenCount = 0;
    let oddCount = 0;

    while(c<n){
        a = b;
        b = c;
        c = a + b;
        if(c % 2 == 0){
            evenSum += c;
            console.log(`evenSum: ${evenSum} from fibNum: ${evenSum-c-2}`);
            evenCount += 1;
        } else {
            oddCount += 1;
        }
    }
    console.log(`even fib numbers within ${n} is: ${evenCount}` + `\n odd numbers are: ${oddCount}`);
    return evenSum;
}